/** Hobby-flavoured fragments for default list names (kebab-case). */
const PREFIXES = [
  "meeple",
  "cube",
  "card",
  "dice",
  "tile",
  "deck",
  "bag",
  "rail",
  "hex",
  "worker",
  "dungeon",
  "engine",
  "tableau",
  "rondel",
  "draft",
  "auction",
  "area",
  "bluff",
  "coop",
  "legacy",
  "euro",
  "crunchy",
  "gateway",
  "filler",
  "heavy",
  "solo",
  "party",
  "dexterity",
  "push-luck",
  "roll-write",
  "bag-build",
  "deck-build",
  "tile-lay",
  "worker-place",
  "hidden-role",
  "victory",
  "wood",
  "glass",
  "mini",
  "train",
  "ship",
  "castle",
  "market",
  "guild",
  "farm",
  "quest",
  "campaign",
  "scenario",
  "expansion",
  "deluxe",
  "pledge",
  "stretch",
  "solo-mode",
  "two-player",
  "kingmaking",
  "analysis",
  "point-salad",
];

const SUFFIXES = [
  "draft",
  "build",
  "crawl",
  "night",
  "run",
  "express",
  "route",
  "trade",
  "ship",
  "lay",
  "flip",
  "bid",
  "score",
  "block",
  "spin",
  "march",
  "tower",
  "salad",
  "rush",
  "hour",
  "quest",
  "saga",
  "tales",
  "legacy",
  "campaign",
  "bits",
  "beads",
  "tray",
  "insert",
  "sleeves",
  "mat",
  "standee",
  "boss",
  "minion",
  "loot",
  "raid",
  "village",
  "city",
  "kingdom",
  "guild",
  "harbor",
  "vineyard",
  "pasture",
  "meadow",
  "forge",
  "mill",
  "track",
  "line",
  "loop",
  "chain",
  "combo",
  "engine",
  "tableau",
  "meeples",
  "cubes",
  "cards",
  "dice",
  "tiles",
  "tracks",
];

function pick<T>(xs: readonly T[]): T {
  return xs[Math.floor(Math.random() * xs.length)]!;
}

/** Random hyphenated hobby name, e.g. `meeple-night` or `engine-salad`. */
export function generateRandomBoardGameListName(): string {
  return `${pick(PREFIXES)}-${pick(SUFFIXES)}`;
}

/** Name not already present in `existing` keys (retry a few times). */
export function uniqueRandomListName(existing: Set<string>): string {
  for (let i = 0; i < 64; i++) {
    const n = generateRandomBoardGameListName();
    if (!existing.has(n)) return n;
  }
  return `${generateRandomBoardGameListName()}-${Date.now().toString(36)}`;
}
